export enum TranslateFields {
	time_period = 'Временной период',
	product_type = 'Тип продукта',
	new_users = 'Новые пользователи',
	new_users_accumulation = 'Всего пользователей, накопительным итогом',
	dau_accumulation = 'Активные пользователи',
	revenue = 'Выручка',
	payments_quantity = 'Количество оплат',
	payments_users_quantity = 'Количество оплативших пользователей',
	mean_payment_amount = 'Средний чек',
	arpu = 'ARPU',
	arppu = 'ARPPU',
	tokens_total = 'Потрачено пользователями всего',
	tokens_paid_users = 'Потрачено бесплатными пользователями',
	tokens_free_users = 'Потрачено платными пользователями',
	tokens_gpt_total = 'Всего потрачено токенов GPT',
	tokens_gpt_paid_users = 'Потрачено платными пользователями GPT',
	tokens_gpt_free_users = 'Потрачено бесплатноми пользователями GPT',
	tokens_dalle_total = 'Всего потрачено токенов Dalle',
	tokens_dalle_paid_users = 'Потрачено платными пользователями Dalle',
	tokens_dalle_free_users = 'Потрачено бесплатноми пользователями Dalle',
	tokens_stable_diffusion_total = 'Всего потрачено токенов SD',
	tokens_stable_diffusion_paid_users = 'Потрачено платными пользователями SD',
	tokens_stable_diffusion_free_users = 'Потрачено бесплатноми пользователями SD',
	retention = 'Retention',
	ltv = 'LTV',
}
